// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jlntafmozkvfjvmxhdmf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpsbnRhZm1vemt2Zmp2bXhoZG1mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1MDgxNTAsImV4cCI6MjA2NDA4NDE1MH0.bLjMSs0MD1cQY2mVDLcqphSUmypldq1Milc9bk5R9Z4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);